sudo: false
language: python
python: "3.4"

install:
  - pip install wand
  - pip install PyPDF2
  - pip install typing
  - pip install pillow
  - pip install python-magic
  - pip install preview-generator
  - pip install pytest

# command to run tests
script: "cd ${TRAVIS_BUILD_DIR} && py.test tests"


                              