sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - libreoffice

install:
  - python setup.py install
  - pip install preview-generator
  - pip install pytest

# command to run tests
script: "cd ${TRAVIS_BUILD_DIR} && py.test tests"


                              